"""New migration

Revision ID: 32791f056c4b
Revises: 
Create Date: 2023-04-12 10:11:20.161884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32791f056c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sign_up_source', sa.Enum('VK', 'TELEGRAM', 'WEBSITE', name='sign_up_source'), nullable=False),
    sa.Column('id_on_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('licensor',
    sa.Column('licensor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('passport_issue_date', sa.Date(), nullable=False),
    sa.Column('registration', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('licensor_id')
    )
    op.create_table('release',
    sa.Column('release_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('licensor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('release_type', sa.Enum('SINGLE', 'EP', 'LP', 'MIXTAPE', name='release_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('on_sale_date', sa.Date(), nullable=False),
    sa.Column('cover', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('upc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['licensor_id'], ['licensor.licensor_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('release_id')
    )
    op.create_table('track',
    sa.Column('track_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('release_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('music_writer', sa.String(), nullable=False),
    sa.Column('text_writer', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('number_on_tracklist', sa.Integer(), nullable=False),
    sa.Column('tiktok_timing', sa.Integer(), nullable=True),
    sa.Column('explicit_content', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('karaoke_text', sa.String(), nullable=True),
    sa.Column('isrc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.release_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    op.drop_table('release')
    op.drop_table('licensor')
    op.drop_table('user')
    # ### end Alembic commands ###
