"""models1

Revision ID: 6780bb5cc03a
Revises: 
Create Date: 2023-04-08 23:39:10.738441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6780bb5cc03a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sign_up_source', sa.Enum('VK', 'TELEGRAM', 'WEBSITE', name='sign_up_source'), nullable=False),
    sa.Column('id_on_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('licensors',
    sa.Column('licensor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('passport_issue_date', sa.Date(), nullable=False),
    sa.Column('registration', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('licensor_id')
    )
    op.create_table('releases',
    sa.Column('release_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('release_type', sa.Enum('SINGLE', 'EP', 'LP', 'MIXTAPE', name='release_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('on_sale_date', sa.Date(), nullable=False),
    sa.Column('cover', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('upc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('release_id')
    )
    op.create_table('tracks',
    sa.Column('track_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('release_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('number_on_tracklist', sa.Integer(), nullable=False),
    sa.Column('isrc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.release_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('releases')
    op.drop_table('licensors')
    op.drop_table('users')
    # ### end Alembic commands ###
