"""fix track

Revision ID: 903d84c77511
Revises: 6780bb5cc03a
Create Date: 2023-04-09 00:09:27.195291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903d84c77511'
down_revision = '6780bb5cc03a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('music_writer', sa.String(), nullable=False))
    op.add_column('tracks', sa.Column('text_writer', sa.String(), nullable=False))
    op.add_column('tracks', sa.Column('tiktok_timing', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('explicit_content', sa.Boolean(), nullable=False))
    op.add_column('tracks', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('karaoke_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'karaoke_text')
    op.drop_column('tracks', 'text')
    op.drop_column('tracks', 'explicit_content')
    op.drop_column('tracks', 'tiktok_timing')
    op.drop_column('tracks', 'text_writer')
    op.drop_column('tracks', 'music_writer')
    # ### end Alembic commands ###
