"""order

Revision ID: b0f90868edba
Revises: cfd89a6351a7
Create Date: 2023-04-21 14:50:05.449224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0f90868edba'
down_revision = 'cfd89a6351a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('release_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'MODERATION', 'PROBLEM', 'CANCELED', 'COMPLETED', name='order_status'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.release_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.add_column('release', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'is_active')
    op.drop_table('order')
    # ### end Alembic commands ###
